workflows:
  ios-workflow:
    name: iOS Free Build

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign

      - cd build/ios/iphoneos
      - mkdir Payload
      - mv Runner.app Payload
      - zip -r Runner.ipa Payload

    artifacts:
      - build/ios/iphoneos/Runner.ipa
